import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Platypi } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const platypi = Platypi({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Veloretti Cycle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={platypi.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
